### ISSUE TITLE
AR Features dont work

### ISSUE THREAD

**Issue by tuniax** [PixelOS-Devices/device_xiaomi_lisa#10]
Hello, I have a problem with the augmented reality feature. When I try to use an AR function in an app, the app crashes.

Tested with:
 - Amazon Shopping ("See it in space" feature).

- Google Maps ("Live View" function)

Buildnumber:

TQA1A.230105.001.A2
PixelOS_lisa-13.0-20230129-1023

**Comment by ComradeWave** [comment]
[crash-com-google-android-apps-maps-17_05-07-42-17_337.zip](https://github.com/PixelOS-Devices/device_xiaomi_lisa/files/15351088/crash-com-google-android-apps-maps-17_05-07-42-17_337.zip)
Adding a crash log to help the developer

**Comment by whyredfire** [comment]
Works on latest release [PixelOS_lisa-14.0-20240804-0932.zip](https://sourceforge.net/projects/pixelos-releases/files/fourteen/lisa/PixelOS_lisa-14.0-20240804-0932.zip/download).
