### ISSUE TITLE
Wifi android 14 problem 

### ISSUE THREAD

**Issue by strolowanyszyk** [PixelOS-Devices/device_xiaomi_lisa#13]
After trying to turn on WiFi on phone, it automatically turns off and cannot be turned on.

**Comment by dkpost3** [comment]
add sepolicy/private/system_server.te

```
#Allow system_server to read wifi_hal_prop
get_prop(system_server, wifi_hal_prop)
```
[and replace configs/wifi/wpa_supplicant_overlay.conf
](https://github.com/dkpost3/android_device_xiaomi_sm8350-common/commit/3dba2b852cb08bd3e06ebef5acd93dd4a7e25b53)

**Comment by markg85** [comment]
Is there a new release with this fix? The current latest release (https://pixelos.net/download/lisa from 22 dec 2023) has this issue for me.

**Comment by thaibeouu** [comment]
> add sepolicy/private/system_server.te
> 
> ```
> #Allow system_server to read wifi_hal_prop
> get_prop(system_server, wifi_hal_prop)
> ```
> 
> [and replace configs/wifi/wpa_supplicant_overlay.conf ](https://github.com/dkpost3/android_device_xiaomi_sm8350-common/commit/3dba2b852cb08bd3e06ebef5acd93dd4a7e25b53)

@dkpost3 do you know the steps needed to build this repo? I cloned it and tried to run `./setup-makefiles.sh` but met with `Unable to find helper script at ./../../../tools/extract-utils/extract_utils.sh`, not sure where to find that

**Comment by dkpost3** [comment]
@thaibeouu 
https://github.com/LineageOS/android_tools_extract-utils/blob/lineage-21.0/extract_utils.sh
