### ISSUE TITLE
Fast battery drain on Pixel os android 14

### ISSUE THREAD

**Issue by mooncoffee1** [PixelOS-Devices/device_xiaomi_lisa#14]
My battery drains too fast, like from 100% to 60 % in like 40 mins, but if I activate internet or location its even worse, what to do to fix that? it's maybe a kernel problem, I don't know, someone help me please

**Comment by sadorowo** [comment]
i also have this issue, Android 14, UQ1A.240105.004.A1
PixelOS_miatoll-14.0-20240120-1557
