### ISSUE TITLE
usb audio output not working properly

### ISSUE THREAD

**Issue by JuanDavidVL** [PixelOS-Devices/device_xiaomi_lisa#15]
USB audio output does not work in the general system, only in a few applications that use it exclusively. 

Even if the USB audio device is disconnected, the phone audio stops working until the system is rebooted.

**Comment by whyredfire** [comment]
Check in the latest release [PixelOS_lisa-14.0-20240804-0932.zip](https://sourceforge.net/projects/pixelos-releases/files/fourteen/lisa/PixelOS_lisa-14.0-20240804-0932.zip/download).
