### ISSUE TITLE
Caller id issue

### ISSUE THREAD

**Issue by S-nehra** [PixelOS-Devices/device_xiaomi_lisa#16]
When someone call me... My number get append with caller number on Airtel sim...if I change sim slot it have that issue in that slot also... But when I change my phone... No issue with that sim... But if put another sim in my pixelos phone... It again have same issue.
Seriously issue as not able to detect called as saved number donot recognise the number

Pixelos 27may2024

**Comment by whyredfire** [comment]
Fixed on [PixelOS_lisa-14.0-20240804-0932.zip](https://sourceforge.net/projects/pixelos-releases/files/fourteen/lisa/PixelOS_lisa-14.0-20240804-0932.zip/download).
